version: '3'

volumes:
  pg_data:
  static_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static_volume:/app/collected_static
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /app/collected_static
    volumes:
      - static_volume:/app/collected_static
  gateway:
    build: ./gateway/
    env_file: .env
    volumes:
      - static_volume:/app/collected_static
    ports:
      - 8000:80 